// Exercise icons bundled locally to avoid runtime network requests.
export const EXERCISE_IMAGE_ASSETS: Record<string, any> = {
  'Ab Wheel Rollout': require("../assets/images/exercises/ab-wheel-rollout.png"),
  'Alternate Dumbbell Front Raise': require("../assets/images/exercises/alternate-dumbbell-front-raise.png"),
  'Alternating Dumbbell Curl': require("../assets/images/exercises/alternating-dumbbell-curl.png"),
  'Arnold Press': require("../assets/images/exercises/arnold-press.png"),
  'Bench Press': require("../assets/images/exercises/bench-press.png"),
  'Bent Knee Reverse Crunches': require("../assets/images/exercises/bent-knee-reverse-crunches.png"),
  'Bent over Rows': require("../assets/images/exercises/bent-over-rows.png"),
  'Bent Over Rows Supinated Grip': require("../assets/images/exercises/bent-over-rows-supinated-grip.png"),
  'Bent-Over Lateral Raise': require("../assets/images/exercises/bent-over-lateral-raise.png"),
  'Bent-Over Row (Single Arm)': require("../assets/images/exercises/bent-over-row-single-arm.png"),
  'Bicycle Crunch': require("../assets/images/exercises/ab-wheel-rollout.png"),
  'Box Jumps': require("../assets/images/exercises/box-jumps.png"),
  'Bulgarian Split Squat': require("../assets/images/exercises/bulgarian-split-squat.png"),
  'Cable Pull Through': require("../assets/images/exercises/cable-pull-through.png"),
  'Chest dips': require("../assets/images/exercises/chest-dips.png"),
  'Chest Fly': require("../assets/images/exercises/chest-fly.png"),
  'Chest Press Machine': require("../assets/images/exercises/chest-press-machine.png"),
  'Close-Grip Pulldown': require("../assets/images/exercises/close-grip-pulldown.png"),
  'Concentration Curl': require("../assets/images/exercises/concentration-curl.png"),
  'Crossover': require("../assets/images/exercises/crossover.png"),
  'Crunches': require("../assets/images/exercises/ab-wheel-rollout.png"),
  'Curl': require("../assets/images/exercises/curl.png"),
  'Deadlift': require("../assets/images/exercises/deadlift.png"),
  'Declined Bench Press': require("../assets/images/exercises/declined-bench-press.png"),
  'Donkey Calf Raise': require("../assets/images/exercises/donkey-calf-raise.png"),
  'Face Pull': require("../assets/images/exercises/face-pull.png"),
  'Front Raise': require("../assets/images/exercises/front-raise.png"),
  'Front Squat': require("../assets/images/exercises/front-squat.png"),
  'Hack Squat': require("../assets/images/exercises/hack-squat.png"),
  'Hammer Curl': require("../assets/images/exercises/hammer-curl.png"),
  'Hanging Leg Raise': require("../assets/images/exercises/hanging-leg-raise.png"),
  'High Cable Rear Delt Fly': require("../assets/images/exercises/high-cable-rear-delt-fly.png"),
  'Hip Thrust': require("../assets/images/exercises/hip-thrust.png"),
  'Incline Bench Press': require("../assets/images/exercises/incline-bench-press.png"),
  'Incline Chest Fly': require("../assets/images/exercises/incline-chest-fly.png"),
  'Incline Curl': require("../assets/images/exercises/incline-curl.png"),
  'Kickback': require("../assets/images/exercises/kickback.png"),
  'Lateral Raise': require("../assets/images/exercises/lateral-raise.png"),
  'Leg Extension': require("../assets/images/exercises/leg-extension.png"),
  'Leg Press': require("../assets/images/exercises/leg-press.png"),
  'Leg Press Calf Raise': require("../assets/images/exercises/leg-press.png"),
  'Leg Raises': require("../assets/images/exercises/hanging-leg-raise.png"),
  'Lunge': require("../assets/images/exercises/lunge.png"),
  'Lying Leg Curl': require("../assets/images/exercises/lying-leg-curl.png"),
  'Lying Triceps Extension': require("../assets/images/exercises/lying-triceps-extension.png"),
  'Mountain Climbers': require("../assets/images/exercises/mountain-climbers.png"),
  'Oblique Crunch': require("../assets/images/exercises/oblique-crunch.png"),
  'One-Arm Lateral Raise': require("../assets/images/exercises/one-arm-lateral-raise.png"),
  'Overhead Triceps Extension': require("../assets/images/exercises/overhead-triceps-extension.png"),
  'Parallel Dip Bar': require("../assets/images/exercises/parallel-dip-bar.png"),
  'Pec Deck': require("../assets/images/exercises/pec-deck.png"),
  'Plank': require("../assets/images/exercises/plank.png"),
  'Preacher Curl': require("../assets/images/exercises/preacher-curl.png"),
  'Pull Up': require("../assets/images/exercises/pull-up.png"),
  'Pull Up with a Supinated Grip': require("../assets/images/exercises/pull-up-with-a-supinated-grip.png"),
  'Pullover': require("../assets/images/exercises/pullover.png"),
  'Push Press': require("../assets/images/exercises/push-press.png"),
  'Push Ups': require("../assets/images/exercises/push-ups.png"),
  'Reverse Grip Triceps Extension': require("../assets/images/exercises/reverse-grip-triceps-extension.png"),
  'Reverse Pec Deck': require("../assets/images/exercises/reverse-pec-deck.png"),
  'Reverse-Grip Pulldown': require("../assets/images/exercises/reverse-grip-pulldown.png"),
  'Romanian Deadlift': require("../assets/images/exercises/romanian-deadlift.png"),
  'Rope Ab Pulldown': require("../assets/images/exercises/rope-ab-pulldown.png"),
  'Rope Pulldown': require("../assets/images/exercises/rope-pulldown.png"),
  'Rope Pushdown': require("../assets/images/exercises/rope-pushdown.png"),
  'Russian Twist': require("../assets/images/exercises/oblique-crunch.png"),
  'Seated Cable Row': require("../assets/images/exercises/seated-cable-row.png"),
  'Seated Calf Raise': require("../assets/images/exercises/donkey-calf-raise.png"),
  'Seated French Press': require("../assets/images/exercises/seated-french-press.png"),
  'Seated Leg Curl': require("../assets/images/exercises/seated-leg-curl.png"),
  'Seated Shoulder Press': require("../assets/images/exercises/seated-shoulder-press.png"),
  'Side Plank': require("../assets/images/exercises/plank.png"),
  'Single Leg Calf Raise': require("../assets/images/exercises/single-leg-calf-raise.png"),
  'Single Leg Deadlift': require("../assets/images/exercises/single-leg-deadlift.png"),
  'Single Leg Extension': require("../assets/images/exercises/leg-extension.png"),
  'Single-Arm Front Raise': require("../assets/images/exercises/single-arm-front-raise.png"),
  'Single-Arm Low Pulley Cable Curl': require("../assets/images/exercises/single-arm-low-pulley-cable-curl.png"),
  'Single-arm Seated Cable Row': require("../assets/images/exercises/bent-over-row-single-arm.png"),
  'Single-Arm Triceps Extension': require("../assets/images/exercises/single-arm-triceps-extension.png"),
  'Squat': require("../assets/images/exercises/bulgarian-split-squat.png"),
  'Standing Calf Raise': require("../assets/images/exercises/single-leg-calf-raise.png"),
  'Standing Shoulder Press': require("../assets/images/exercises/standing-shoulder-press.png"),
  'Step Ups': require("../assets/images/exercises/step-ups.png"),
  'Straight Arm Lat Pulldown': require("../assets/images/exercises/straight-arm-lat-pulldown.png"),
  'Straight Bar Low Pulley Cable Curl': require("../assets/images/exercises/straight-bar-low-pulley-cable-curl.png"),
  'T-Bar Rows': require("../assets/images/exercises/t-bar-rows.png"),
  'Triceps Pressdown': require("../assets/images/exercises/triceps-pressdown.png"),
  'Upright Row': require("../assets/images/exercises/upright-row.png"),
  'Wide-Grip Pulldown': require("../assets/images/exercises/wide-grip-pulldown.png"),
};

export function getExerciseImageUrl(exerciseName: string): any | undefined {
  return EXERCISE_IMAGE_ASSETS[exerciseName];
}
